### ISSUE TITLE
Add Data Collection Files

### ISSUE THREAD

**Issue by julianweisbord** [julianweisbord/Deep-Learning-For-Object-Recognition-on-a-Mobile-Robot#4]
Add all of the files necessary to do our ROS data collection process to this repo. Inside the readme, add dependencies and important environment variables.

**Comment by Rodrigmi** [comment]
Just created pull request for this issue

**Comment by julianweisbord** [comment]
Traditionally, people don't close an issue until it is merged into its target branch. There might still be some extra changes that need to be made which are discovered in the review process.
